- README.md
Users stumbling on this repository should be able to quickly start using the tool after reading the README
- Add link to releases page
- Add header to each listed command
- Use codeblocks for CLI examples (as they highlight the parameters and are easier to copy)
- Lint README with [markdownlint](https://github.com/DavidAnson/markdownlint)
> Tweak README, add link to releases

- internal/template/dashboard.go
- internal/template/load_test.go
When creating a dashboard `variable_id` is matched with `name` instead of `variable_name`
Match `variable_id` with `variable_name`
> Match thing variable_name with dashboard variable_id

- .github/workflows/check-dependencies-task.yml
- .github/workflows/release-go-task.yml
- .github/workflows/test-go-task.yml
This PR fixes some deprecation warnings that are being returned when GitHub actions are run, e.g.:
> The `set-output` command is deprecated and will be disabled soon.
> Node.js 12 actions are deprecated.
- Replaced `set-output` command with its [new counterpart](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/#examples)
- Updated checkout action from v2 to v3
- Updated setup-go action from v2 to v3
N/A
> Fix GitHub actions warnings

- .licenses/go/github.com/arduino/iot-client-go.dep.yml
- README.md
- cli/device/create.go
- command/device/create.go
- command/device/creategeneric.go
- go.mod
- go.sum
- internal/iot/client.go
We want to allow the user to create a device with the selected connectivity when more than one connectivity is avilable
- Go client updated
- "connection" parameter added to the device create command
> Manage connection parameter for device create

- .github/workflows/sync-binaries-task.yml
- .licenses/go/github.com/arduino/iot-client-go.dep.yml
- README.md
- cli/device/create.go
- command/device/board.go
- command/device/create.go
- command/device/creategeneric.go
- command/ota/generate.go
- firmware/generator.py
- go.mod
- go.sum
- internal/iot/client.go
We want to support the Opta device in the cloud-acli
- Added device Opta fqbn in crypto fqbn list
- Added Opta fqbn and product ID in the OTA bin generation process
- Added Opta fqbn in provisioning bin generation
- Added Opta fqbn in the sync binaries workflow
https://arduino.atlassian.net/browse/IOT-2273
> [IOT-2273] Add opta support

- command/ota/generate.go
- internal/ota/encoder.go
We want to manage the OTA update for ESP32 boards
- In case of OTA and ESP32 fqbn, a fix magic number is added to the .bin file used for the ota
https://arduino.atlassian.net/browse/IOT-2272
> [IOT-2272] Manage ESP32 OTA

- .github/workflows/sync-binaries-task.yml
- README.md
- command/device/board.go
- command/ota/generate.go
- firmware/generator.py
This PR adds GIGA boards support to the arduino-cloud-cli.
- Added support for provisioning GIGA boards
- Minor doc fix
Jira issue: [https://arduino.atlassian.net/browse/IOT-2358](https://arduino.atlassian.net/browse/IOT-2358)
> [IOT-2358] Add support for GIGA

- README.md
Update README with instructions about dependency from 'arduino-cli' to create a device
The creation of a device requires the `arduino-cli` installed, but this is not stated anywhere in the docs.
The documentation should be improved to reflect this dependency.
Updated README file with the proposed improvements.
Closes #136 
* [N/A] Changes are covered by tests.
* [N/A] Logging is meaningful in case of troubleshooting.
> Update README with instructions about dependency from 'arduino-cli'

- .github/workflows/check-dependencies-task.yml
- .github/workflows/test-go-task.yml
- DistTasks.yml
- go.mod
Bumping golang version to `1.17` allows to update some of this project's dependencies.
Golang version is updated to `1.17` in `go.mod` and in this project's workflows and `DistTasks.yml.`
Related to https://github.com/arduino/arduino-cloud-cli/issues/110
> Bump golang to version 1.17

- internal/template/extract.go
Currently, when the configuration of a thing is exported, the timezone is ignored. So if a user use the extracted template to create a new thing, a default timezone is assigned
- Timezone is exported in the thing export command
https://arduino.atlassian.net/browse/IOT-2732
> [IOT-2732] Export timezone for things

- .github/workflows/release-go-task.yml
- gon.config.hcl
An excellent tool named [gon](https://github.com/mitchellh/gon) was used to perform the notarization.
the latest stable release of gon uses the altool command-line utility for notarization:
https://github.com/mitchellh/gon/blob/v0.2.5/notarize/upload.go#L41
Using altool for notarization is now deprecated by Apple and support for notarization via this tool is scheduled to be disabled 2023-11-01:
https://developer.apple.com/news/?id=y5mjxqmn
Furthermore, gon was archived.
I switched to https://github.com/Bearer/gon that has included https://github.com/mitchellh/gon/pull/72, hoping the maintainers will take the responsibility of maintaining the project.
I added also `AC_PROVIDER` env var which is mandatory with the new notarytool.
See …
>  Replace mitchellh/go used for macOS notarization

- cli/credentials/init.go
The `arduino-cloud-cli credentials init` command prints a helpful message providing the user with guidance about how to obtain the Arduino Cloud API credentials.
It seems the URL of the Arduino Cloud API Keys page changed due to restructuring of the site since the time this message was written. A redirect was not set up from the old URL to the new URL so the previous URL in the message now only redirects to the Arduino Cloud home page:
> To obtain your API credentials visit https://create.arduino.cc/iot/integrations
The URL is hereby updated to the modern URL of the API Keys page: https://app.arduino.cc/api-keys
Although the incorrect/missing redirect should also be fixed, it is still best to avoid a reliance on such redirects since they tend to be ephemeral.
> Update API credentials URL in `credentials init` message

- internal/template/filter.go
When a dashboard containing a scheduler widget is exported, and then a new dashboard is created from the exported template, the options of a scheduler widget are lost in the process. As a consequence, the GUI (both Web and Mobile) can't render the scheduler widget.
> [WIRE-244] Fix: export options of a scheduler widget in the dashboard extract command

- DistTasks.yml
Upgrading build container versions for armel/darwin. Debian 10 containers have been removed from support.
> Upgrading build container versions for armel/darwin

- cli/ota/status.go
- command/ota/status.go
- internal/ota-api/dto.go
- internal/ota-api/dto_test.go
Add support for fetch progress for ota download
> Support for ota download progress

- cli/device/list.go
- command/device/list.go
- internal/template/extract.go
Add device filtering capability based on device status
> Device filtering by status

- command/ota/status.go
- internal/ota-api/dto.go
- internal/ota-api/dto_test.go
Align CLI to new OTA service capabilities to report download progress bar. Output example:
`arduino-cloud-cli$ ./arduino-cloud-cli ota status -o cce28885-5c33-42f4-9fdc-98dd0f326c11
Device ID                            Ota ID                               Status    Started At           Ended At
7996c05a-7841-46c0-b34e-f1c9a49a50bb cce28885-5c33-42f4-9fdc-98dd0f326c11 Succeeded 2024-07-25T09:38:25Z 2024-07-25T09:39:17Z
Details:
Time                 Status    Detail
2024-07-25T09:39:04Z Reboot
2024-07-25T09:39:04Z Flash
2024-07-25T09:39:01Z Fetch     [====================] 100.00% (firmware size: 730279 bytes)
2024-07-25T09:38:30Z Fetch
2024-07-25T09:38:25Z Start
2024-07-25T09:38:25Z Available
`
> Ota progress status details with progress bar fixes

- .github/workflows/check-dependencies-task.yml
- .github/workflows/release-go-task.yml
According to github deprecation notes, upgrade deprecated actions (upload/download) to v4
> Upgrade deprecated github actions

- .github/workflows/check-dependencies-task.yml
A breaking change was made in the 3.2.1 release of the [**actions/upload-artifact**](https://github.com/actions/upload-artifact) action (https://github.com/actions/upload-artifact/issues/602), without doing a major version bump as would be done in a responsibly maintained project. The action now defaults to not uploading "hidden" files.
This project's "**Check Go Dependencies**" workflow uses the [**Licensed**](https://github.com/github/licensed) tool to check for incompatible dependency licenses. The dependencies license metadata cache used by **Licensed** is stored in a folder named `.licensed`.
In order to facilitate updates, the workflow uploads the generated dependencies license metadata cache as a [workflow artifact](https://docs.github.com/actions/writing-workflows/choosing-what-you …
> Configure actions/upload-artifact action to upload required hidden files

- .github/workflows/release-go-task.yml
> Fix MacOS release

- .github/workflows/check-dependencies-task.yml
- .github/workflows/release-go-task.yml
- .github/workflows/test-go-task.yml
- .licenses/go/github.com/arduino/iot-client-go/v3.dep.yml
- .licenses/go/golang.org/x/oauth2.dep.yml
- .licenses/go/golang.org/x/oauth2/clientcredentials.dep.yml
- .licenses/go/golang.org/x/oauth2/internal.dep.yml
- command/dashboard/dashboard.go
- command/device/createlora.go
- command/device/device.go
- command/device/provision.go
- command/ota/massupload.go
- command/ota/massupload_test.go
- command/template/apply.go
- command/thing/bind.go
- command/thing/thing.go
- go.mod
- go.sum
- internal/iot/client.go
- internal/iot/error.go
- internal/iot/token.go
- internal/template/dashboard.go
- internal/template/extract.go
- internal/template/load.go
- internal/template/load_test.go
Upgrade iot client GO to version 3.0.0
> Upgrade iot client GO to version 3.0.0

- DistTasks.yml
Fix compile image for darwin/arm6
> Fix compile image for darwin/arm6

- .github/workflows/release-go-task.yml
- DistTasks.yml
- gon.config.hcl
> Distribution fixes for MacOS

- .licenses/go/github.com/arduino/iot-client-go/v3.dep.yml
- .licenses/go/golang.org/x/oauth2.dep.yml
- .licenses/go/golang.org/x/oauth2/clientcredentials.dep.yml
- .licenses/go/golang.org/x/oauth2/internal.dep.yml
- command/device/show.go
- go.mod
- go.sum
- internal/iot/client_test.go
- internal/template/load_test.go
Updating iot-clients to latest version for compatibility reasons.
Updating iot-client-go to fix serializtion problem in case of API unknown fields (behavior change introduced by swagger go generator).
> [WIRE-717] Fix unknown fields serialization issue
